### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by codetaylor** [GetConfluxed/Biome-Specific-Dungeons#2]
I'm getting a `NoClassDefFound` when loading a pack: https://gist.github.com/codetaylor/015e9bc1eaec0c45867942dcfdfaeff6

It looks the same as #1, but I do have `Bookshelf-1.12.2-2.3.577`.

Peeking in the lib clearly shows the class is there:
![image](https://user-images.githubusercontent.com/1240716/54644152-e7043900-4a55-11e9-8e57-363c16488424.png)

I'm at a loss...

**Comment by codetaylor** [comment]
I noticed there [aren't any dependencies](https://github.com/GetConfluxed/Biome-Specific-Dungeons/blob/master/src/main/java/net/darkhax/biomespecificdungeons/BiomeSpecificDungeons.java#L15) listed for bookshelf, could the mod be loading before the lib?

**Comment by Darkhax** [comment]
Yeah, there is a load order issue with the mod.

**Comment by Darkhax** [comment]
I thought I had already fixed this issue, and it turns out I had. You are using an outdated version of the mod (1.0.3 has the fix). You also linked to the master branch but I built off the 1.12.2 branch which has the fix.

**Comment by codetaylor** [comment]
Oops! Thanks for your time :)
