### ISSUE TITLE
Crash on load with BiomeSpecificDungeons-1.12.2-1.0.3 and Bookshelf-1.12.2-2.3.577

### ISSUE THREAD

**Issue by YaibaToKen** [GetConfluxed/Biome-Specific-Dungeons#3]
https://pastebin.com/Ee16RwqZ

**Comment by Darkhax** [comment]
Do you have any custom files here? The issue is that it's loading `data/opencomputers|core/biomespecificdungeons/spawner` and the `|` character is not valid.

**Comment by YaibaToKen** [comment]
So that would make it a problem with OpenComputers instead then? As I use no custom files of my own.

**Comment by Darkhax** [comment]
Ah, I see what's going on here. Technically it is a problem with OpenComputers but this is actually on me. Will fix soon.

**Comment by YaibaToKen** [comment]
Alright, thanks for the time and hope it's an easy fix

**Comment by Darkhax** [comment]
Unfortunately this has not been a simple issue to fix. I tried to implement my own version of the 1.13+ data pack system in 1.12 and I think it's safe to call it a partially-failed experiment at this point. Now that Mojang's data pack system is more complex in newer versions I will be switching over to that which will not have this issue. 1.12 versions will not be getting any future updates.
